site_name: "LLM 4 Horizon"
# theme: landing
nav:
  - Home: index.md
  - Installation:
      - Ollama: install/ollama.md
      - Docker Desktop: install/docker.md
      - Open WebUI: install/open-webui.md
      - All In One: install/all-in-one.md
  - Usage: usage.md
